version: "3.9"  # optional since v1.27.0
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
